version: "3.9"

services:
  app:
    build: .
    container_name: rental
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}&channelBinding=${DB_CHANNEL_BINDING}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
    volumes:
      - ./uploads:/app/uploads
