version: "3.9"

services:
  rental:
    build: .
    container_name: rental_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
